proxy-groups:
  - name: 手动选择
    type: select
    proxies:
  - name: PROXY
    type: select
    proxies:
      - ⚖️ 负载均衡-散列
      - ⚖️ 负载均衡-轮询
      - 手动选择
      - DIRECT
  - name: p1
    type: url-test
    url: http://www.apple.com/library/test/success.html
    interval: 500
    proxies:
      - 1
  - name: ⚖️ 负载均衡-散列
    type: load-balance
    url: http://www.apple.com/library/test/success.html
    interval: 300
    strategy: consistent-hashing
    proxies:
      - 1
  - name: ⚖️ 负载均衡-轮询
    type: load-balance
    url: http://www.apple.com/library/test/success.html
    interval: 300
    strategy: round-robin
    proxies:
      - 1
